// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import { Montserrat_Alternates, Albert_Sans } from "next/font/google"
import Image from "next/image"

const montserratAlt = Montserrat_Alternates({
  variable: "--montserrat-alternates",
  subsets: ["latin"],
  weight: "700",
})

const albert = Albert_Sans({
  variable: "--albert-sans",
  subsets: ["latin"],
  weight: "400",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${montserratAlt.variable} ${albert.variable}`}>
        <header>
          <nav className="flex justify-between py-1.5 px-5">
            <Image
              src="/printforge-logo-icon.svg"
              alt="printforge logo"
              width={40}
              height={40}
              className="md:hidden"
            />
            <Image
              src="/printforge-logo.svg"
              alt="printforge logo"
              width={180}
              height={40}
              className="hidden md:block"
            />
            <div className="flex gap-8 py-2">
              <p className="uppercase">3D Models</p>
              <p className="uppercase">About</p>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
