// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import { Montserrat_Alternates, Albert_Sans } from "next/font/google"
import Image from "next/image"
import logoIcon from "@/public/printforge-logo-icon.svg"
import fullLogo from "@/public/printforge-logo.svg"
import Link from "next/link"
import { LayoutProps } from "./types"
import Navbar from "./components/Navbar"

const montserratAlt = Montserrat_Alternates({
  variable: "--montserrat-alternates",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
})

const albert = Albert_Sans({
  variable: "--albert-sans",
  subsets: ["latin"],
  // weight: "400",
  display: "swap",
})

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${montserratAlt.variable} ${albert.variable} flex flex-col min-h-screen`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  )
}
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
